spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/event_aggregator
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true